main: uk.co.deixel.deixutils.DeixUtils
name: DeixUtils
version: 1.4
api-version: 1.16
commands:
  nethercoords:
    description: Show the coordinates to place a portal in the other dimention to make it end up at your current coordinates.
    usage: /nethercoords
  saycoords:
    description: Say your current block coords in chat.
    usage: /saycoords
  togglediscord:
    description: Disable sending and listening for Discord messages.
    usage: /togglediscord
    permission: deixutils.cmds.togglediscord
  config:
    description: Set a plugin config setting.
    usage: /config <setting> <value>
    permission: deixutils.cmds.config
  resetbeds:
    description: Reset beds
    usage: /resetbeds
    permission: deixutils.cmds.resetbeds
  debugbeds:
    description: Reset beds
    usage: /debugbeds
    permission: deixutils.cmds.debugbeds
  debugdiff:
    description: Debug difficulty
    usage: /debugdiff
    permission: deixutils.cmds.debugdiff
permissions:
  deixutils.*:
    description: All permissions for plugin
    default: true
    children:
      deixutils.cmds: true
  deixutils.cmds:
    description: All command permissions
    default: true
    children:
      deixutils.cmds.*: true
  deixutils.cmds.config:
      description: Permission to change plugin settings
      default: op
  deixutils.cmds.togglediscord:
      description: Permission to toggle Discord sending/listening
      default: op
  deixutils.cmds.resetbeds:
      description: Permission to reset beds
      default: op
  deixutils.cmds.debugbeds:
      description: Permission to debug beds
      default: op